spring:
  rabbitmq:
    host: 39.105.104.203
    port: 5672
    username: user1
    password: guest
  datasource:
    url: jdbc:mysql://39.105.181.72/ncc-cloud?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: anti
    password: lenovoL430
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
management:
  security:
    enabled: false

#mabatis数库查询实体接受返回值空值也显示key值
mybatis:
  configuration:
    call-setters-on-nulls: true


##timeout config
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 10000
          strategy: SEMAPHORE
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
  MaxAutoRetries: 2
  MaxAutoRetriesNextServer: 1
  eureka:
    enabled: true

zuul:
  max:
    host:
      connections: 500
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  retryable: true
test: 1111
##feign的配置项:
feign:
  ##启动feign的断路器功能
  hystrix:
    enabled: true
  compression:
    request:
      min-request-size: 2048
      mime-types:
      - text/xml, application/xml, application/json
    response:
      enabled: true