zuul:
  routes:
    api-feign:
      path: /feign/**
      service-id: feign
    api-a-client:
      path: /a-client/**
      service-id: a-client
    api-b-client:
      path: /b-client/**
      service-id: b-client
    api-ncc-cloud-base:
      path: /ncc-cloud-base/**
      service-id: ncc-cloud-base
    api-ncc-cloud-login:
      path: /ncc-cloud-login/**
      service-id: ncc-cloud-login
    api-ncc-cloud-user:
      path: /ncc-cloud-user/**
      service-id: ncc-cloud-user
    api-ncc-cloud-label:
      path: /ncc-cloud-label/**
      service-id: ncc-cloud-label
    api-ncc-cloud-JWT:
      path: /ncc-cloud-online/**
      service-id: ncc-cloud-JWT