spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
management:
  security:
    enabled: false
##timeout config
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
  MaxAutoRetries: 2
  MaxAutoRetriesNextServer: 1
  eureka:
    enabled: true

zuul:
  max:
    host:
      connections: 500
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  retryable: true
  routes:
    api-feign:
      path: /feign/**
      service-id: feign
    api-a-client:
      path: /a-client/**
      service-id: a-client
    api-b-client:
      path: /b-client/**
      service-id: b-client
    api-ncc-cloud-base:
      path: /ncc-cloud-base/**
      service-id: ncc-cloud-base
    api-ncc-cloud-login:
      path: /ncc-cloud-login/**
      service-id: ncc-cloud-login
    api-ncc-cloud-user:
      path: /ncc-cloud-user/**
      service-id: ncc-cloud-user
    api-ncc-cloud-label:
      path: /ncc-cloud-label/**
      service-id: ncc-cloud-label